config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "ui_kit", to: "pages#ui_kit"
  resources :lessons
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  # primary_abstract_class
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :lesson
end

app/models/category.rb
class Category < ApplicationRecord
  CATEGORIES = Category.all.map{ |category| category.name }
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  geocoded_by :address
  belongs_to :user
  belongs_to :category
  has_many :questions
  has_many :bookings, dependent: :destroy
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :lesson
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lessons, dependent: :destroy
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    category = Category.find_by(name: params[:category])
    if params[:category].present?
      @lessons = Lesson.where(category: category)
      else
      @lessons = Lesson.all
    end
      @markers = @lessons.map do |lesson|
        {
          lat: lesson.latitude,
          lng: lesson.longitude
        }
      end
  end

  def new
    @lesson = Lesson.new
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

  def create
    @lesson = Lesson.new(lesson_params)
    @lesson.user = current_user
    if @lesson.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  private

  def lesson_params
    params.require(:lesson).permit(:title, :description, :places, :start_date, :end_date, :category, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home, :ui_kit ]

  def home
  end

  def ui_kit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>COACHING4LIFE</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> %>
    <%# <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
  <%= render "shared/navbar" %>


    <%= yield %>

    <%# <script src="https://cdn.j1sdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
    <script>feather.replace()</script>
  </body>
</html>

app/views/lessons/index.html.erb
<div class="index">
<div class="container">
<%= form_tag(lessons_path, method: :get, class:"row col-8 bg-white p-3 my-3 align-items-center  rounded-pill shadow-sm d-flex justify-content-between") do %>
    <div>
    <%= text_field_tag :city, "city", class:"" %>

    <%= select_tag(:category, options_for_select(Category::CATEGORIES)) %>
    <%= submit_tag("Search") %>
    </div>
  <% end %>
<h3>Our courses:</h3>
<div class="row">
<div class="container">
  <div class="row col-8">
    <% @lessons.each do |lesson| %>
      <div class="col-6">
        <div>
          <%= link_to lesson_path(lesson), class: "card-links" do %>
            <%= render "shared/card_index", lesson: lesson %>
          <% end %>
        </div>
      </div>
     <% end %>
  </div>
  <div class="row col-6">
   <div  style="width: 100%; height: 400px; margin-bottom: 200px;"
        data-controller="mapbox"
        data-mapbox-markers-value="<%= @markers.to_json %>"
        data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
  </div>
</div>
</div>
<%= render "shared/footer" %>
</div>

app/views/lessons/show.html.erb
<div class="container">

  <div class="row">
    <div class="col-8">
      <div class="bg-white my-4 py-3 px-4 shadow-lg rounded">
        <div class="d-flex justify-content-between align-items-center">
          <h2 class="m-0"><strong><%= @lesson.title %></strong></h2>
          <h4 class="m-0"><span class="badge alert-primary"><%= @lesson.places %> places available</span></h4>
        </div>
      </div>
      <div class="rounded-5">
        <%# <%= cl_image_tag @lesson.photo.key, height: 225px;, width: 100, crop: :fill, class: "object-fit-cover'" %>
        <%= image_tag "https://images.unsplash.com/photo-1509062522246-3755977927d7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3032&q=80", class:"w-100 rounded", style:"height: 300px; object-fit: cover;" %>
      </div>
      <div class="bg-white my-4 py-3 px-4 shadow-lg rounded">
        <div class="d-flex align-items-center justify-content-between">
          <h3 class="m-0">Description</h3>
          <h4 class="m-0"><span class="badge alert-success"><%= @lesson.category.name %></span></h4>
        </div>
        <p class="my-2"><%= @lesson.description %></p>
      </div>
    </div>

    <div class="col-4 mt-4" data-controller="answers">
      <%= render "shared/book_course" %>
      <%= render "shared/answer_question" %>
    </div>

  </div>
</div>

app/views/pages/home.html.erb
<div class="background"></div>
<div class="homepage" style=" width: 100%; vertical-align: middle;">
  <div class="my_container">

  <div class="row">

    <div class="col-8">
      <div class="ban-body">
        <h1> Let's make someone's life better. <u>Together.</u> </h1>
        <p> Browse through our library of courses and coaching lessons. Learn valuable skills, for work, life and everything in between </p>
        <p> Become a coach to offer free coaching sessions to refugees. </p>
      </div>
    </div>
    <div class="col-4">
      <div class="animation">
        <%= image_tag("illustration.svg") %>
      </div>
    </div>
    <div class="col-8">
      <div class="info">
        <div class="bg-white p-4 m-3 rounded shadow-lg" style="width: 400px;">
          <div class="d-flex align-items-center justify-content-between">
            <div class="d-flex align-items-center">
              <p> lasnfljadfgn.adj gnadg nadkjgv adg bd,g badg</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-8">
      <div class="info">
        <div class="bg-white p-4 m-3 rounded shadow-lg" style="width: 400px;">
          <div class="d-flex align-items-center justify-content-between">
            <div class="d-flex align-items-center">
              <p> lasnfljadfgn.adj gnadg nadkjgv adg bd,g badg</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-8">
      <div class="info">
        <div class="bg-white p-4 m-3 rounded shadow-lg" style="width: 400px;">
          <div class="d-flex align-items-center justify-content-between">
            <div class="d-flex align-items-center">
              <p> lasnfljadfgn.adj gnadg nadkjgv adg bd,g badg</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-8">
      <div class="info">
        <div class="bg-white p-4 m-3 rounded shadow-lg" style="width: 400px;">
          <div class="d-flex align-items-center justify-content-between">
            <div class="d-flex align-items-center">
              <p> lasnfljadfgn.adj gnadg nadkjgv adg bd,g badg</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/ui_kit.html.erb
<%= render "shared/card_index" %>
<%= render "shared/navbar" %>
<%= render "shared/search_form_home" %>
<%= render "shared/book_course" %>
<%= render "shared/sidebar_profile.html" %>

app/views/shared/_activity_dash.html.erb
<div class="bg-white p-4 w-75 h-100 m-3">
  <h3 class="mb-3 text-secondary">Activity</h3>
  <ul class="nav nav-pills">
    <li class="nav-item">
      <%= link_to "All", "#", class: "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to "Pending", "#", class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Resolved", "#", class: "nav-link" %>
    </li>
  </ul>

  <%# CARRD GRID BELOW %>


</div>

app/views/shared/_answer_question.html.erb
<div class="bg-white p-4 w-100 rounded-3 shadow-lg" style="display: none;" data-answers-target="answerbox">
  <h3 class="mb-3">One more step</h3>
  <%= simple_form_for(root_path) do |f| %>
    <p><strong><%= @lesson.questions[0].content %></strong></p>
    <%= f.input :answer %>

    <p><strong><%= @lesson.questions[1].content  %></strong></p>
    <%= f.input :answer %>

    <p><strong><%= @lesson.questions[2].content  %></strong></p>
    <%= f.input :answer, placeholder: "Your answer", label: false %>

    <%= f.submit :Next, class: "btn btn-lg btn-primary w-100 mt-2" %>
  <% end %>
</div>

app/views/shared/_book_course.html.erb
<div class="bg-white p-4 w-25 mr=0 rounded-3 shadow-lg sticky-lg-top w-100" data-answers-target="requestbox">

  <h3 class="mb-3">Book this course</h3>

  <div class="mb-3">
    <p class="text-secondary mb-1"><small>OFFERED BY</small></p>
    <div class="d-flex justify-content-between align-items-center">
      <div class="m-0">
        <h5 class="mb-1 fw-bold"><%= @lesson.user.first_name %> <%= @lesson.user.last_name %></h5>
        <p class="m-0"><%= @lesson.user.description %></p>
      </div>
      <div class="m-2"><%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png", class: "avatar-medium" %></div>
    </div>

  </div>

  <hr>

  <div class="mb-3">
    <p class="text-secondary m-0"><small>DATES</small></p>
    <div class="d-flex justify-content-between align-items-center">
      <h5 class="my-1"><%= @lesson.start_date.strftime("%a %d %b") %></h5>
      <h5 class="my-1">-</h5>
      <h5 class="my-1"><%= @lesson.end_date.strftime("%a %d %b") %></h5>
    </div>
  </div>

  <%= link_to "Request", "#", class: "btn btn-lg btn-primary w-100 mt-2", data: {action: "click->answers#request"} %>

</div>

app/views/shared/_card_index.html.erb
<div class="mb-4">
  <div>
    <%# <%= cl_image_tag @lesson.photo.key, style:"width: 400px; object-fit: cover;" %>
    <%= image_tag "https://www.sgl28.com/wp-content/uploads/2020/10/ruby.jpeg", class:"rounded-top", style:"width: 401px; object-fit: cover;" %>
  </div>
  <div class="bg-white p-4 rounded-bottom shadow-lg" style="width: 400px;">
  <div class="d-flex align-items-center justify-content-between">
    <div class="d-flex align-items-center">
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png", class: "avatar-small" %>
      <p class="my-0 mx-2"><strong><%= lesson.user.first_name %> <%= lesson.user.last_name %></strong></p>
    </div>
    <div class="badge alert-danger"><%= lesson.places %>/10 places available</div>
  </div>
  <div class="d-flex align-items-center justify-content-between mt-2">
    <h5 class="mt-2"><%= lesson.title %></h5>
    <p class="m-0"><%= lesson.start_date.strftime("%a %d %b") %> - <%= lesson.end_date.strftime("%a %d %b")  %></p>
  </div>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="text-center text-white" style="background-color: #21081a;">

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    Made with ❤️ at <a class="text-white" href="https://lewagon.com/">LeWagon</a> in Amsterdam
  </div>
  <!-- Copyright -->
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon">
  <div class="my_container d-flex align-items-center justify-content-between">
    <%= link_to "Coaching4Life", "#", class: "navbar-brand"%>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Home", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "About", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "About", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <i data-feather="menu" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search_form_home.html.erb
<div class="bg-white p-4 w-25 m-3 rounded-3 shadow-lg">
  <h3 class="mb-3">Search for a course</h3>
  <%= simple_form_for(root_path) do |f| %>
    <%= f.input :location %>
    <%= f.input :category, :collection => %w[Learn_Language IT Fighting] %>
    <%= f.submit :Search, class: "btn btn-primary w-100 mt-2" %>
  <% end %>
</div>

app/views/shared/_sidebar_profile.html.erb
<div class="bg-white p-4 w-25 h-100 m-3 rounded-3 shadow-lg">
  <h5 class="mb-3 text-center"><strong>PROFILE</strong></h5>
  <div class="text-center">
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png", class: "avatar-large m-3" %>
    <h4 class="mt-3">Denis Gavrilenco</h4>
    <p class="mt-3">Lorem ipsum dolor sit amet consectetur
    adipisicing elit. Velit incidunt ad tempore
    reiciendis quos delectus hic reprehenderit, excepturi
    asperiores ut sed facere possimus doloribus quod consequuntur autem.
    Dignissimos, numquam voluptatibus!</p>
  </div>
  <%= link_to "Post a course", "#", class: "btn btn-primary w-100 mt-2" %>
  <%= link_to "Log out", "#", class: "btn btn-link text-danger w-100 mt-2" %>

</div>